### ISSUE TITLE
No Explanation about the functionality

### ISSUE THREAD

**Issue by Juff-Ma** [mcwwi/lib-rcon#3]
this isnt really a problem but i think it's really anoying to not know how to work with the lib.
the main rcon isn't really the problem but the map and nbt stuff gets really really anoying (in fact so annoying that i won't even know how to use it).

please add a wiki or a documentation (i think that's more or less the same), the VS `<summary>`
 isn't enough

sorry for the english

Edit: i don't think he's answering because he commited nothing for over 4 years so if someone understands it, please fork and write a wiki! I bet you 🙇‍♂️.

**Comment by chiefmultihat** [comment]
This is an older library.  I'm updating so items can be pulled out.  The
nbt stuff helps decode the mca files.  I can create a few console projects
that explain what it does.

**Comment by chiefmultihat** [comment]
Actually - I've been working on this for quite some time, just haven't updated a new library yet - because really - I don't have a wiki or documentation and didn't want to update without it :)

The new library repository re-orgs all the code.  May contain a couple of projects that extract out the code into assemblies to prevent pulling in un-needed functionality. 

I think I have it up to .NET 5/6 and working on getting it to .NET 7 (worry about that a little later)
The new code also has Azure cosmos/blob storage services, fluent ftp.
The library not only is an RCON interface, but also a server utility with asynchronous processing to ftp region files off the minecraft server.  It's broken down into units to allow customization in how to go about processing minecraft data.  

If RCON is all you need, then you should be able to extract the needed classes.

**Comment by Juff-Ma** [comment]
Thank you I'm writing a little Rcon manager in .net 6 at the time. And I found your library and wanted to include all the features but I'm seriously not good enough to look through the classes and find the point to start with maps

**Comment by Juff-Ma** [comment]
P.s.: because you said it's not just an Rcon library. And may question why I then need this. I wanted to include several extra stuff like (eventually later) writing a spigot plugin to control the server better but that's music of the future (I don't know if this phrase exits in English)

**Comment by chiefmultihat** [comment]
@Juff-Ma You can reach me draycmhdev@gmail.com, I'll try to help you use the library if you would like.

**Comment by Juff-Ma** [comment]
thank you but i first want to finish the main functionality :), but later i'll come back to this.
